import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Service",
    description: "Generated by create next app",
  };
  
export default function ServiceLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          
        >
          {children}
        </body>
      </html>
    );
  }
  